---
- name: Install and start the Apache HTTPD
  hosts: stupid
  tasks:
   - name: httpd package is present 
     yum:
        name: 
        - bind
        - bind-utils
        state: present
#tasks 2
   - name: adding dhcplines
     blockinfile:
       dest: /etc/named.conf
       block: |
        options {
                listen-on port 53 { any; };
                listen-on-v6 port 53 { ::1; };
                directory       "/var/named";
                dump-file       "/var/named/data/cache_dump.db";
                statistics-file "/var/named/data/named_stats.txt";
                memstatistics-file "/var/named/data/named_mem_stats.txt";
                allow-query     { any; };
                recursion yes;
                forwarders { 8.8.8.8; };
                forward first;
                dnssec-enable yes;
                dnssec-validation yes;
                bindkeys-file "/etc/named.iscdlv.key";

                managed-keys-directory "/var/named/dynamic";
        };

        logging {
                channel default_debug {
                        file "data/named.run";
                        severity dynamic;
                };
        };

        zone "." IN {
               type hint;
               file "named.ca";
        };
        zone "vm6.com" IN {
                type slave;
                file "/var/named/vm6.com.fwd";
                masters { 192.168.1.60; };
        };
        zone "1.168.192.in-addr.arpa" IN {
        type slave;
        file "/var/named/vm6.com.rev";
        masters { 192.168.1.60; } ;
        };
        include "/etc/named.rfc1912.zones";
        include "/etc/named.root.key";
       backup: yes




   - name: Copy and replace the index.html
     copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0775
#task 3
   - name: Start service httpd, if not running
     service:
        name: httpd
        state: started
        enabled: yes


