---
- name: asdasd
  hosts: try2
  vars:
    sv:
      - iptables
      - vsftpd
      - dhcpd
      - httpd
      - named
      - nfs
  tasks:
  - name: restart services
    service:
      name: "{{item}}"
      state: stopped
    with_items:
      - "{{sv}}"
